### ISSUE TITLE
Implementation for get_and_pre_process_dataset missing

### ISSUE THREAD

**Issue by aarepuu** [cut-dicl/ais2eta#1]
Hello

I wanted to test out the code out of the box to reproduce the results, but the implementation for `get_and_pre_process_dataset` with function `get_and_pre_process_dataset` is missing from the codebase.  Is that intentionally left out from the source code?

I would imagine that it is a classic x, y split matrix, but would be good to see if there is any additional logic for splitting you apply for the data. 

Thanks

**Comment by cut-dicl** [comment]
We have added the missing `get_and_pre_process_dataset` file and made a few other improvements.
